(function(){
"use strict";
var B="/activities/yalla-8th-anniversary",F={"code":0,"data":{"result":0,"status":0,"state":0,"fState":0,"fSort":1,"isFirst":false,"isReceive":true,"reachCount":0,"totalNum":0,"remainNum":0,"freeLotteryNum":0,"count":0,"countdown":0,"score":0,"point":0,"points":0,"level":0,"stage":0,"process":0,"percent":0,"id":0,"rewardId":0,"rewardStatus":0,"tagType":0,"prettyId":"—","nickName":"","nickname":"","headUrl":"","headurl":"","teamId":-1,"kavipLv":-1,"signUpRegion":0,"showMemory":false,"needCount":0,"countryId":0,"ranking":-1,"list":[],"res":[],"items":[],"records":[],"rankList":[],"memberList":[],"taskList":[],"rewardIds":[],"rewards":[],"rewardDtoList":[],"questionList":[],"headUrls":[],"propInfo":[],"rankInfo":[],"myInfo":{"headurl":"","nickname":"","num":0,"countryId":0,"ranking":-1,"kavipLv":0,"teamCode":0,"teamUrl":""},"userInfo":{"headurl":"","nickname":"","num":0,"countryId":0,"ranking":-1,"kavipLv":0,"teamCode":0,"teamUrl":""},"propConfigs":[{"id":0,"status":0,"count":0},{"id":0,"status":0,"count":0},{"id":0,"status":0,"count":0},{"id":0,"status":0,"count":0},{"id":0,"status":0,"count":0},{"id":0,"status":0,"count":0},{"id":0,"status":0,"count":0},{"id":0,"status":0,"count":0}],"rewardInfos":[{"rewardId":1,"rewardStatus":0,"status":0,"count":0},{"rewardId":2,"rewardStatus":0,"status":0,"count":0},{"rewardId":3,"rewardStatus":0,"status":0,"count":0}]},"count":0,"timeShow":1,"countdown":0,"list":[],"res":[],"message":"Archived activity: anonymous read-only state"},S={"result":0,"status":0,"state":0,"fState":0,"fSort":1,"isFirst":false,"isReceive":true,"reachCount":0,"totalNum":0,"remainNum":0,"freeLotteryNum":0,"count":0,"countdown":0,"score":0,"point":0,"points":0,"level":0,"stage":0,"process":0,"percent":0,"id":0,"rewardId":0,"rewardStatus":0,"tagType":0,"prettyId":"—","nickName":"","nickname":"","headUrl":"","headurl":"","teamId":-1,"kavipLv":-1,"signUpRegion":0,"showMemory":false,"needCount":0,"countryId":0,"ranking":-1,"list":[],"res":[],"items":[],"records":[],"rankList":[],"memberList":[],"taskList":[],"rewardIds":[],"rewards":[],"rewardDtoList":[],"questionList":[],"headUrls":[],"propInfo":[],"rankInfo":[],"myInfo":{"headurl":"","nickname":"","num":0,"countryId":0,"ranking":-1,"kavipLv":0,"teamCode":0,"teamUrl":""},"userInfo":{"headurl":"","nickname":"","num":0,"countryId":0,"ranking":-1,"kavipLv":0,"teamCode":0,"teamUrl":""},"propConfigs":[{"id":0,"status":0,"count":0},{"id":0,"status":0,"count":0},{"id":0,"status":0,"count":0},{"id":0,"status":0,"count":0},{"id":0,"status":0,"count":0},{"id":0,"status":0,"count":0},{"id":0,"status":0,"count":0},{"id":0,"status":0,"count":0}],"rewardInfos":[{"rewardId":1,"rewardStatus":0,"status":0,"count":0},{"rewardId":2,"rewardStatus":0,"status":0,"count":0},{"rewardId":3,"rewardStatus":0,"status":0,"count":0}]},I={"userId":"0","region":"0","token":"","v":"9999","appVersionCode":9999,"s":"1","roomID":0,"recentRoomID":0,"userToken":"","statusHeight":0},L=[],E=[];
window.__YALLA_REPLAY__={officialSpa:true,readOnly:true,fixture:"fixtures/api/_fallback.json",ledger:L,errors:E};
try{localStorage.setItem("hasavif",JSON.stringify("noavif"));localStorage.setItem("haswebp",JSON.stringify("nowebp"));localStorage.removeItem("supportWebp");localStorage.removeItem("supportAvif")}catch(e){}
function api(v){try{return /\/(?:api|Api)\//.test(new URL(String(v),location.href).pathname)}catch(e){return false}}
function payload(v){var p="";try{p=new URL(String(v),location.href).pathname}catch(e){p=String(v)}var n=p.split("/").pop()||"";if(/Init$/i.test(n))return{code:0,data:0,count:0,timeShow:1,countdown:0,list:[],res:[]};if(/GetCopywritingAddress$/i.test(n))return{code:0,data:"{}"};if(B.indexOf("yalla-9th-anniversary")>=0&&/GetRank$/i.test(n))return{code:0,data:{myInfo:S.myInfo,rankList:[]}};if(B.indexOf("yalla-season-2025")>=0&&/GetRankInfo$/i.test(n))return{code:0,data:{rankInfo:[],userInfo:S.userInfo}};var list=/(?:rank|list|top\d*|log|barrage|record|history|members?|cards?|props?|items?|tasks?)(?:info)?$/i.test(n);return{code:0,data:list?[]:S,count:0,timeShow:1,countdown:0,list:[],res:[],message:"Archived activity: anonymous read-only state"}}
function note(k,u){L.push({kind:k,url:String(u),external:false,at:Date.now()})}
var nf=window.fetch&&window.fetch.bind(window);if(nf)window.fetch=function(i,n){var u=typeof i==="string"?i:i.url;if(api(u)){note("fetch",u);return Promise.resolve(new Response(JSON.stringify(payload(u)),{status:200,headers:{"Content-Type":"application/json"}}))}return nf(i,n)};
var N=window.XMLHttpRequest;
function X(){this.n=new N;this.l={};this.h={};this.a=false;this.rs=0;this.st=0;this.rt="";this.r=null;this.ty="";this.to=0;this.wc=false}
X.prototype.open=function(m,u,a,user,pw){this.m=m;this.u=String(u);this.a=api(u);this.as=a!==false;if(this.a){this.rs=1;this.emit("readystatechange")}else this.n.open(m,u,a===undefined?true:a,user,pw)};
X.prototype.send=function(b){var s=this;if(this.a){note("xhr",this.u);var done=function(){var f=payload(s.u);s.st=200;s.rs=4;s.rt=JSON.stringify(f);s.r=s.ty==="json"?f:s.rt;s.emit("readystatechange");s.emit("load");s.emit("loadend")};this.as?setTimeout(done,0):done();return}this.n.responseType=this.ty;this.n.timeout=this.to;this.n.withCredentials=this.wc;Object.keys(this.h).forEach(function(k){s.n.setRequestHeader(k,s.h[k])});["readystatechange","load","loadend","error","abort","timeout","progress"].forEach(function(t){s.n.addEventListener(t,function(e){s.emit(t,e)})});this.n.send(b)};
X.prototype.abort=function(){this.a?(this.emit("abort"),this.emit("loadend")):this.n.abort()};X.prototype.setRequestHeader=function(k,v){this.h[k]=v};X.prototype.getAllResponseHeaders=function(){return this.a?"content-type: application/json\r\n":this.n.getAllResponseHeaders()};X.prototype.getResponseHeader=function(k){return this.a&&String(k).toLowerCase()==="content-type"?"application/json":this.n.getResponseHeader(k)};X.prototype.addEventListener=function(t,f){(this.l[t]||(this.l[t]=[])).push(f)};X.prototype.removeEventListener=function(t,f){this.l[t]=(this.l[t]||[]).filter(function(x){return x!==f})};X.prototype.emit=function(t,e){e=e||{type:t,target:this,currentTarget:this};var h=this["on"+t];if(typeof h==="function")h.call(this,e);(this.l[t]||[]).slice().forEach(function(f){f.call(this,e)},this)};
Object.defineProperties(X.prototype,{readyState:{get:function(){return this.a?this.rs:this.n.readyState}},status:{get:function(){return this.a?this.st:this.n.status}},statusText:{get:function(){return this.a?"OK":this.n.statusText}},responseText:{get:function(){return this.a?this.rt:this.n.responseText}},response:{get:function(){return this.a?this.r:this.n.response}},responseURL:{get:function(){return this.a?location.origin+this.u:this.n.responseURL}},responseType:{get:function(){return this.ty},set:function(v){this.ty=v}},timeout:{get:function(){return this.to},set:function(v){this.to=v}},withCredentials:{get:function(){return this.wc},set:function(v){this.wc=v}},upload:{get:function(){return this.n.upload}}});window.XMLHttpRequest=X;
function act(n){return function(){note("bridge",n)}}function inf(){return JSON.stringify(I)}
window.Yalla=Object.assign({},window.Yalla||{},{getInfo:inf,coinNotEnoughQuick:act("coin"),downloadPage:act("download"),goToRecharge:act("recharge"),quickRecharch:act("recharge"),shareActivity:act("share"),shareThird:act("share")});window.webkit=window.webkit||{};window.webkit.messageHandlers=window.webkit.messageHandlers||{};["closeLoading","coinNotEnough","downloadPage","quickRecharch","rechargePage","roomPage","shareActivityToFriends","shareThird"].forEach(function(n){window.webkit.messageHandlers[n]=window.webkit.messageHandlers[n]||{postMessage:act(n)}});window.webkit.messageHandlers.getInfo=window.webkit.messageHandlers.getInfo||{postMessage:function(){setTimeout(function(){["getInfoH5","getInfoCallBack","getInfoCallback"].forEach(function(n){if(typeof window[n]==="function")try{window[n](JSON.stringify(I))}catch(e){}})},0)}};
window.open=function(u){u&&String(u).indexOf(B)===0?location.href=u:note("blocked-open",u);return null};window.addEventListener("error",function(e){E.push(String(e.message||e.error||"error"))});window.addEventListener("unhandledrejection",function(e){E.push(String(e.reason||"unhandled rejection"))});document.documentElement.setAttribute("data-yalla-replay","ready")})();
