ALTER TABLE MessageRecord ADD COLUMN isread INTEGER DEFAULT 1;
ALTER TABLE MessageRecord ADD COLUMN msgstatus INTEGER DEFAULT 1;
ALTER TABLE ChatMessage ADD COLUMN msgstatus INTEGER DEFAULT 1;
ALTER TABLE FriendsTable ADD COLUMN ctime INTEGER;