ALTER TABLE MessageRecord ADD COLUMN role INTEGER DEFAULT 0;
ALTER TABLE FriendsTable ADD COLUMN  role INTEGER DEFAULT 0;
ALTER TABLE UserRecord ADD COLUMN vip INTEGER DEFAULT 0;
ALTER TABLE UserRecord ADD COLUMN vipLevel INTEGER DEFAULT 0;
ALTER TABLE UserRecord ADD COLUMN sex INTEGER DEFAULT 0;
ALTER TABLE UserRecord ADD COLUMN prettyId INTEGER DEFAULT 0;
ALTER TABLE UserRecord ADD COLUMN role INTEGER DEFAULT 0;