#sdcard 相关配置 解析key对应的value 以“，”切割成数组
#注：该配置内容须为UTF-8编码
#可能的sdcard命名列表，可以添加
possible_sdcard_names:sd,SD,Sd,sD,card,emmc,emulated,storage
#不可能的sdcard命名列表 可以添加
#eg:usb,usbdisk,udisk,disk,otg,drive
#暂时不用
#impossible_sdcard_names:usb,disk,otg,drive