package com.amazonaws.regions;

import com.amazonaws.logging.Log;
import com.amazonaws.logging.LogFactory;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import p080o000OoO.o0Oo0oo;

/* JADX INFO: loaded from: classes2.dex */
public class RegionUtils {

    /* JADX INFO: renamed from: OooO00o, reason: collision with root package name */
    public static ArrayList f12329OooO00o;

    /* JADX INFO: renamed from: OooO0O0, reason: collision with root package name */
    public static final Log f12330OooO0O0 = LogFactory.OooO0O0("com.amazonaws.request");

    public static Region OooO00o(String str) {
        ArrayList<Region> arrayList;
        synchronized (RegionUtils.class) {
            if (f12329OooO00o == null) {
                OooO0O0();
            }
            arrayList = f12329OooO00o;
        }
        for (Region region : arrayList) {
            if (region.f12324OooO00o.equals(str)) {
                return region;
            }
        }
        return null;
    }

    public static synchronized void OooO0O0() {
        if (System.getProperty("com.amazonaws.regions.RegionUtils.fileOverride") != null) {
            try {
                OooO0Oo();
            } catch (FileNotFoundException e) {
                throw new RuntimeException("Couldn't find regions override file specified", e);
            }
        }
        if (f12329OooO00o == null) {
            OooO0OO();
        }
        if (f12329OooO00o == null) {
            throw new RuntimeException("Failed to initialize the regions.");
        }
    }

    public static void OooO0OO() {
        Log log = f12330OooO0O0;
        if (log.OooO0O0()) {
            log.OooO0oO("Initializing the regions with default regions");
        }
        ArrayList arrayList = new ArrayList();
        Region regionOooO00o = o0Oo0oo.OooO00o("af-south-1", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o, "autoscaling", "autoscaling.af-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o, "dynamodb", "dynamodb.af-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o, "ec2", "ec2.af-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o, "elasticloadbalancing", "elasticloadbalancing.af-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o, "kms", "kms.af-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o, "lambda", "lambda.af-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o, "logs", "logs.af-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o, "s3", "s3.af-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o, "sns", "sns.af-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o, "sqs", "sqs.af-south-1.amazonaws.com");
        Region regionOooO00o2 = o0Oo0oo.OooO00o("ap-northeast-1", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o2, "autoscaling", "autoscaling.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "cognito-identity", "cognito-identity.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "cognito-idp", "cognito-idp.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "cognito-sync", "cognito-sync.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "data.iot", "data.iot.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "dynamodb", "dynamodb.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "ec2", "ec2.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "elasticloadbalancing", "elasticloadbalancing.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "firehose", "firehose.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "iot", "iot.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "kinesis", "kinesis.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "kms", "kms.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "lambda", "lambda.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "logs", "logs.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "polly", "polly.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "s3", "s3.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "sdb", "sdb.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "sns", "sns.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "sqs", "sqs.ap-northeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o2, "sts", "sts.amazonaws.com");
        Region regionOooO00o3 = o0Oo0oo.OooO00o("ap-northeast-2", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o3, "autoscaling", "autoscaling.ap-northeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o3, "cognito-identity", "cognito-identity.ap-northeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o3, "cognito-idp", "cognito-idp.ap-northeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o3, "cognito-sync", "cognito-sync.ap-northeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o3, "data.iot", "data.iot.ap-northeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o3, "dynamodb", "dynamodb.ap-northeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o3, "ec2", "ec2.ap-northeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o3, "elasticloadbalancing", "elasticloadbalancing.ap-northeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o3, "iot", "iot.ap-northeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o3, "kinesis", "kinesis.ap-northeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o3, "kms", "kms.ap-northeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o3, "lambda", "lambda.ap-northeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o3, "logs", "logs.ap-northeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o3, "polly", "polly.ap-northeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o3, "s3", "s3.ap-northeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o3, "sns", "sns.ap-northeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o3, "sqs", "sqs.ap-northeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o3, "sts", "sts.ap-northeast-2.amazonaws.com");
        Region regionOooO00o4 = o0Oo0oo.OooO00o("ap-south-1", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o4, "autoscaling", "autoscaling.ap-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o4, "cognito-identity", "cognito-identity.ap-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o4, "cognito-idp", "cognito-idp.ap-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o4, "cognito-sync", "cognito-sync.ap-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o4, "dynamodb", "dynamodb.ap-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o4, "ec2", "ec2.ap-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o4, "elasticloadbalancing", "elasticloadbalancing.ap-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o4, "kinesis", "kinesis.ap-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o4, "kms", "kms.ap-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o4, "lambda", "lambda.ap-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o4, "logs", "logs.ap-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o4, "polly", "polly.ap-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o4, "s3", "s3.ap-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o4, "sns", "sns.ap-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o4, "sqs", "sqs.ap-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o4, "sts", "sts.amazonaws.com");
        Region regionOooO00o5 = o0Oo0oo.OooO00o("ap-southeast-1", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o5, "autoscaling", "autoscaling.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "cognito-identity", "cognito-identity.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "cognito-idp", "cognito-idp.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "cognito-sync", "cognito-sync.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "data.iot", "data.iot.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "dynamodb", "dynamodb.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "ec2", "ec2.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "elasticloadbalancing", "elasticloadbalancing.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "iot", "iot.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "kinesis", "kinesis.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "kms", "kms.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "lambda", "lambda.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "logs", "logs.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "polly", "polly.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "s3", "s3.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "sdb", "sdb.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "sns", "sns.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "sqs", "sqs.ap-southeast-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o5, "sts", "sts.amazonaws.com");
        Region regionOooO00o6 = o0Oo0oo.OooO00o("ap-southeast-2", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o6, "autoscaling", "autoscaling.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "cognito-identity", "cognito-identity.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "cognito-idp", "cognito-idp.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "cognito-sync", "cognito-sync.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "data.iot", "data.iot.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "dynamodb", "dynamodb.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "ec2", "ec2.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "elasticloadbalancing", "elasticloadbalancing.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "iot", "iot.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "kinesis", "kinesis.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "kms", "kms.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "lambda", "lambda.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "logs", "logs.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "polly", "polly.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "s3", "s3.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "sdb", "sdb.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "sns", "sns.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "sqs", "sqs.ap-southeast-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o6, "sts", "sts.amazonaws.com");
        Region regionOooO00o7 = o0Oo0oo.OooO00o("ca-central-1", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o7, "autoscaling", "autoscaling.ca-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o7, "dynamodb", "dynamodb.ca-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o7, "ec2", "ec2.ca-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o7, "elasticloadbalancing", "elasticloadbalancing.ca-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o7, "kinesis", "kinesis.ca-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o7, "kms", "kms.ca-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o7, "lambda", "lambda.ca-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o7, "logs", "logs.ca-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o7, "polly", "polly.ca-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o7, "s3", "s3.ca-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o7, "sns", "sns.ca-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o7, "sqs", "sqs.ca-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o7, "sts", "sts.amazonaws.com");
        Region regionOooO00o8 = o0Oo0oo.OooO00o("eu-central-1", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o8, "autoscaling", "autoscaling.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "cognito-identity", "cognito-identity.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "cognito-idp", "cognito-idp.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "cognito-sync", "cognito-sync.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "data.iot", "data.iot.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "dynamodb", "dynamodb.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "ec2", "ec2.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "elasticloadbalancing", "elasticloadbalancing.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "firehose", "firehose.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "iot", "iot.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "kinesis", "kinesis.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "kms", "kms.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "lambda", "lambda.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "logs", "logs.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "polly", "polly.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "s3", "s3.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "sns", "sns.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "sqs", "sqs.eu-central-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o8, "sts", "sts.amazonaws.com");
        Region regionOooO00o9 = o0Oo0oo.OooO00o("eu-south-1", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o9, "autoscaling", "autoscaling.eu-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o9, "dynamodb", "dynamodb.eu-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o9, "ec2", "ec2.eu-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o9, "elasticloadbalancing", "elasticloadbalancing.eu-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o9, "lambda", "lambda.eu-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o9, "logs", "logs.eu-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o9, "s3", "s3.eu-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o9, "sns", "sns.eu-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o9, "sqs", "sqs.eu-south-1.amazonaws.com");
        Region regionOooO00o10 = o0Oo0oo.OooO00o("eu-west-1", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o10, "autoscaling", "autoscaling.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "cognito-identity", "cognito-identity.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "cognito-idp", "cognito-idp.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "cognito-sync", "cognito-sync.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "data.iot", "data.iot.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "dynamodb", "dynamodb.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "ec2", "ec2.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "elasticloadbalancing", "elasticloadbalancing.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "email", "email.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "firehose", "firehose.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "iot", "iot.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "kinesis", "kinesis.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "kms", "kms.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "lambda", "lambda.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "logs", "logs.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "machinelearning", "machinelearning.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "polly", "polly.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "rekognition", "rekognition.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "s3", "s3.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "sdb", "sdb.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "sns", "sns.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "sqs", "sqs.eu-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o10, "sts", "sts.amazonaws.com");
        Region regionOooO00o11 = o0Oo0oo.OooO00o("eu-west-2", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o11, "autoscaling", "autoscaling.eu-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o11, "cognito-identity", "cognito-identity.eu-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o11, "cognito-idp", "cognito-idp.eu-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o11, "cognito-sync", "cognito-sync.eu-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o11, "dynamodb", "dynamodb.eu-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o11, "ec2", "ec2.eu-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o11, "elasticloadbalancing", "elasticloadbalancing.eu-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o11, "iot", "iot.eu-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o11, "kinesis", "kinesis.eu-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o11, "kms", "kms.eu-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o11, "lambda", "lambda.eu-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o11, "logs", "logs.eu-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o11, "polly", "polly.eu-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o11, "s3", "s3.eu-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o11, "sns", "sns.eu-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o11, "sqs", "sqs.eu-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o11, "sts", "sts.amazonaws.com");
        Region regionOooO00o12 = o0Oo0oo.OooO00o("eu-west-3", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o12, "autoscaling", "autoscaling.eu-west-3.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o12, "dynamodb", "dynamodb.eu-west-3.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o12, "ec2", "ec2.eu-west-3.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o12, "elasticloadbalancing", "elasticloadbalancing.eu-west-3.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o12, "kinesis", "kinesis.eu-west-3.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o12, "kms", "kms.eu-west-3.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o12, "lambda", "lambda.eu-west-3.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o12, "logs", "logs.eu-west-3.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o12, "polly", "polly.eu-west-3.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o12, "s3", "s3.eu-west-3.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o12, "sns", "sns.eu-west-3.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o12, "sqs", "sqs.eu-west-3.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o12, "sts", "sts.amazonaws.com");
        Region regionOooO00o13 = o0Oo0oo.OooO00o("sa-east-1", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o13, "autoscaling", "autoscaling.sa-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o13, "dynamodb", "dynamodb.sa-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o13, "ec2", "ec2.sa-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o13, "elasticloadbalancing", "elasticloadbalancing.sa-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o13, "kinesis", "kinesis.sa-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o13, "kms", "kms.sa-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o13, "lambda", "lambda.sa-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o13, "logs", "logs.sa-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o13, "polly", "polly.sa-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o13, "s3", "s3.sa-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o13, "sdb", "sdb.sa-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o13, "sns", "sns.sa-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o13, "sqs", "sqs.sa-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o13, "sts", "sts.amazonaws.com");
        Region regionOooO00o14 = o0Oo0oo.OooO00o("us-east-1", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o14, "autoscaling", "autoscaling.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "cognito-identity", "cognito-identity.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "cognito-idp", "cognito-idp.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "cognito-sync", "cognito-sync.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "data.iot", "data.iot.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "dynamodb", "dynamodb.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "ec2", "ec2.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "elasticloadbalancing", "elasticloadbalancing.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "email", "email.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "firehose", "firehose.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "iot", "iot.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "kinesis", "kinesis.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "kms", "kms.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "lambda", "lambda.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "logs", "logs.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "machinelearning", "machinelearning.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "mobileanalytics", "mobileanalytics.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "pinpoint", "pinpoint.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "polly", "polly.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "rekognition", "rekognition.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "s3", "s3.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "sdb", "sdb.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "sns", "sns.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "sqs", "sqs.us-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o14, "sts", "sts.amazonaws.com");
        Region regionOooO00o15 = o0Oo0oo.OooO00o("us-east-2", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o15, "autoscaling", "autoscaling.us-east-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o15, "cognito-identity", "cognito-identity.us-east-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o15, "cognito-idp", "cognito-idp.us-east-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o15, "cognito-sync", "cognito-sync.us-east-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o15, "dynamodb", "dynamodb.us-east-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o15, "ec2", "ec2.us-east-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o15, "elasticloadbalancing", "elasticloadbalancing.us-east-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o15, "firehose", "firehose.us-east-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o15, "iot", "iot.us-east-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o15, "kinesis", "kinesis.us-east-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o15, "kms", "kms.us-east-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o15, "lambda", "lambda.us-east-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o15, "logs", "logs.us-east-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o15, "polly", "polly.us-east-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o15, "s3", "s3.us-east-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o15, "sns", "sns.us-east-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o15, "sqs", "sqs.us-east-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o15, "sts", "sts.amazonaws.com");
        Region regionOooO00o16 = o0Oo0oo.OooO00o("us-west-1", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o16, "autoscaling", "autoscaling.us-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o16, "dynamodb", "dynamodb.us-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o16, "ec2", "ec2.us-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o16, "elasticloadbalancing", "elasticloadbalancing.us-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o16, "kinesis", "kinesis.us-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o16, "kms", "kms.us-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o16, "lambda", "lambda.us-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o16, "logs", "logs.us-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o16, "polly", "polly.us-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o16, "s3", "s3.us-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o16, "sdb", "sdb.us-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o16, "sns", "sns.us-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o16, "sqs", "sqs.us-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o16, "sts", "sts.amazonaws.com");
        Region regionOooO00o17 = o0Oo0oo.OooO00o("us-west-2", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o17, "autoscaling", "autoscaling.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "cognito-identity", "cognito-identity.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "cognito-idp", "cognito-idp.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "cognito-sync", "cognito-sync.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "data.iot", "data.iot.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "dynamodb", "dynamodb.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "ec2", "ec2.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "elasticloadbalancing", "elasticloadbalancing.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "email", "email.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "firehose", "firehose.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "iot", "iot.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "kinesis", "kinesis.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "kms", "kms.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "lambda", "lambda.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "logs", "logs.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "polly", "polly.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "rekognition", "rekognition.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "s3", "s3.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "sdb", "sdb.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "sns", "sns.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "sqs", "sqs.us-west-2.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o17, "sts", "sts.amazonaws.com");
        Region regionOooO00o18 = o0Oo0oo.OooO00o("cn-north-1", "amazonaws.com.cn", arrayList);
        RegionDefaults.OooO00o(regionOooO00o18, "autoscaling", "autoscaling.cn-north-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o18, "cognito-identity", "cognito-identity.cn-north-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o18, "dynamodb", "dynamodb.cn-north-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o18, "ec2", "ec2.cn-north-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o18, "elasticloadbalancing", "elasticloadbalancing.cn-north-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o18, "iot", "iot.cn-north-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o18, "kinesis", "kinesis.cn-north-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o18, "lambda", "lambda.cn-north-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o18, "logs", "logs.cn-north-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o18, "s3", "s3.cn-north-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o18, "sns", "sns.cn-north-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o18, "sqs", "sqs.cn-north-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o18, "sts", "sts.cn-north-1.amazonaws.com.cn");
        Region regionOooO00o19 = o0Oo0oo.OooO00o("cn-northwest-1", "amazonaws.com.cn", arrayList);
        RegionDefaults.OooO00o(regionOooO00o19, "autoscaling", "autoscaling.cn-northwest-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o19, "dynamodb", "dynamodb.cn-northwest-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o19, "ec2", "ec2.cn-northwest-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o19, "elasticloadbalancing", "elasticloadbalancing.cn-northwest-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o19, "kinesis", "kinesis.cn-northwest-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o19, "logs", "logs.cn-northwest-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o19, "s3", "s3.cn-northwest-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o19, "sns", "sns.cn-northwest-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o19, "sqs", "sqs.cn-northwest-1.amazonaws.com.cn");
        RegionDefaults.OooO00o(regionOooO00o19, "sts", "sts.amazonaws.com.cn");
        Region regionOooO00o20 = o0Oo0oo.OooO00o("us-gov-west-1", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o20, "autoscaling", "autoscaling.us-gov-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o20, "dynamodb", "dynamodb.us-gov-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o20, "ec2", "ec2.us-gov-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o20, "elasticloadbalancing", "elasticloadbalancing.us-gov-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o20, "kinesis", "kinesis.us-gov-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o20, "kms", "kms.us-gov-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o20, "lambda", "lambda.us-gov-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o20, "logs", "logs.us-gov-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o20, "rekognition", "rekognition.us-gov-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o20, "s3", "s3.us-gov-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o20, "sns", "sns.us-gov-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o20, "sqs", "sqs.us-gov-west-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o20, "sts", "sts.amazonaws.com");
        Region regionOooO00o21 = o0Oo0oo.OooO00o("eu-north-1", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o21, "autoscaling", "autoscaling.eu-north-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o21, "dynamodb", "dynamodb.eu-north-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o21, "ec2", "ec2.eu-north-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o21, "elasticloadbalancing", "elasticloadbalancing.eu-north-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o21, "firehose", "firehose.eu-north-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o21, "iot", "iot.eu-north-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o21, "kinesis", "kinesis.eu-north-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o21, "kms", "kms.eu-north-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o21, "lambda", "lambda.eu-north-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o21, "logs", "logs.eu-north-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o21, "s3", "s3.eu-north-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o21, "sns", "sns.eu-north-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o21, "sqs", "sqs.eu-north-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o21, "sts", "sts.amazonaws.com");
        Region regionOooO00o22 = o0Oo0oo.OooO00o("ap-east-1", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o22, "autoscaling", "autoscaling.ap-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o22, "dynamodb", "dynamodb.ap-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o22, "ec2", "ec2.ap-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o22, "elasticloadbalancing", "elasticloadbalancing.ap-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o22, "firehose", "firehose.ap-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o22, "kinesis", "kinesis.ap-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o22, "kms", "kms.ap-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o22, "lambda", "lambda.ap-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o22, "logs", "logs.ap-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o22, "polly", "polly.ap-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o22, "s3", "s3.ap-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o22, "sns", "sns.ap-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o22, "sqs", "sqs.ap-east-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o22, "sts", "sts.amazonaws.com");
        Region regionOooO00o23 = o0Oo0oo.OooO00o("me-south-1", "amazonaws.com", arrayList);
        RegionDefaults.OooO00o(regionOooO00o23, "autoscaling", "autoscaling.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "cognito-identity", "cognito-identity.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "cognito-idp", "cognito-idp.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "cognito-sync", "cognito-sync.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "data.iot", "data.iot.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "dynamodb", "dynamodb.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "ec2", "ec2.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "elasticloadbalancing", "elasticloadbalancing.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "firehose", "firehose.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "iot", "iot.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "kinesis", "kinesis.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "kms", "kms.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "lambda", "lambda.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "logs", "logs.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "polly", "polly.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "s3", "s3.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "sdb", "sdb.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "sns", "sns.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "sqs", "sqs.me-south-1.amazonaws.com");
        RegionDefaults.OooO00o(regionOooO00o23, "sts", "sts.amazonaws.com");
        f12329OooO00o = arrayList;
    }

    public static void OooO0Oo() throws FileNotFoundException {
        String property = System.getProperty("com.amazonaws.regions.RegionUtils.fileOverride");
        Log log = f12330OooO0O0;
        if (log.OooO0O0()) {
            log.OooO0oO("Using local override of the regions file (" + property + ") to initiate regions data...");
        }
        FileInputStream fileInputStream = new FileInputStream(new File(property));
        try {
            new RegionMetadataParser();
            f12329OooO00o = RegionMetadataParser.OooO0O0(fileInputStream);
        } catch (Exception e) {
            log.OooOO0O("Failed to parse regional endpoints", e);
        }
    }
}
