ALTER TABLE NewFriendsTable ADD COLUMN isRead INTEGER DEFAULT 1;
ALTER TABLE NewFriendsTable ADD COLUMN gender INTEGER DEFAULT -1;
DELETE FROM SystemMessage;
ALTER TABLE SystemMessage ADD COLUMN isRead INTEGER DEFAULT 1;
DROP TABLE IF EXISTS MessageHead;